#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import default_theme_builders

env.add_source_files(env.scene_sources, "*.cpp")

SConscript("icons/SCsub")

# TinaGodot 2D Lite - Use NotoSans_Regular as default font instead of OpenSans_SemiBold
env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/NotoSans_Regular.woff2",
    env.Run(default_theme_builders.make_fonts_header),
)
