#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "*.cpp")
# Removed 3D imports for 2D Lite version
# env.add_source_files(env.editor_sources, "3d/*.cpp")
